name: Build markmap in main branch

on:
  push:
    branches: [main]
    paths:
      - 'calendar.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install markmap
      - name: Install markmap
        run: npm install -g markmap-cli

      # Build markmap mindmap
      - name: Build markmap mindmap
        run: |
          mkdir -p web
          markmap -o ./web/index.html ./calendar.md
          ls -R ./web

      # Commit & push changes back to main branch
      - name: Commit & Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add web
          git commit -m "Update markmap mindmap [skip ci]" || echo "No changes to commit"
          git push origin main
